name: AWS DEPLOY TO STAGING
# turn off deploy to AWS

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.AWS_DB_HOST }}
      DB_PW: ${{ secrets.AWS_DB_PW}}
      DB_USER: ${{ secrets.AWS_DB_USER }}
      DB_NAME: ${{ secrets.AWS_DB_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "deploy/"
          REMOTE_HOST: "ec2-18-118-140-9.us-east-2.compute.amazonaws.com"
          REMOTE_USER: ubuntu
          TARGET: "nodeapps/cinecloud-backend"
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "Root"
        with:
          hosts: "ubuntu@ec2-18-118-140-9.us-east-2.compute.amazonaws.com"
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          debug: false
          command: |
            cd nodeapps/cinecloud-backend
            npm install
            sudo systemctl stop cinecloud-backend
            sudo cp cinecloud-backend.service /lib/systemd/system/cinecloud-backend.service
            sudo systemctl daemon-reload
            sudo systemctl start cinecloud-backend